# Generated by Django 5.0.4 on 2024-04-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_alter_forecastdata_customer_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdata',
            name='period_month',
            field=models.IntegerField(verbose_name='Период месяца'),
        ),
    ]
