# Generated by Django 5.0.4 on 2024-05-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_forecastdata_seasonal_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='artefact',
            field=models.TextField(default='', verbose_name='Главный бизнес-артефакт'),
        ),
    ]
