# Generated by Django 5.0.4 on 2024-05-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_forecastdata_month_coherenceindicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coherenceindicator',
            name='coherence_level',
            field=models.CharField(max_length=100, verbose_name='Для показателя'),
        ),
        migrations.AlterField(
            model_name='dynamicsindicator',
            name='dynamics_type',
            field=models.CharField(max_length=100, verbose_name='Для показателя'),
        ),
        migrations.AlterField(
            model_name='growthstabilityindicator',
            name='stability_level',
            field=models.CharField(max_length=100, verbose_name='Для показателя'),
        ),
        migrations.AlterField(
            model_name='seasonalityindicator',
            name='seasonality_type',
            field=models.CharField(max_length=100, verbose_name='Для показателя'),
        ),
    ]
