# Generated by Django 5.0.4 on 2024-05-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0009_alter_coherenceindicator_coherence_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coherenceindicator',
            old_name='coherence_level',
            new_name='param',
        ),
        migrations.RenameField(
            model_name='dynamicsindicator',
            old_name='dynamics_type',
            new_name='param',
        ),
        migrations.RenameField(
            model_name='growthstabilityindicator',
            old_name='stability_level',
            new_name='param',
        ),
        migrations.RenameField(
            model_name='seasonalityindicator',
            old_name='seasonality_type',
            new_name='param',
        ),
    ]
