# Generated by Django 5.0.4 on 2024-04-25 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Чистая прибыль')),
                ('profitability', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Рентабельность')),
                ('operating_expenses', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Операционные расходы')),
                ('customer_base', models.IntegerField(verbose_name='Клиентская база')),
                ('employee_count', models.IntegerField(verbose_name='Количество сотрудников')),
                ('period_month', models.IntegerField(verbose_name='Период месяца')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicsIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Значение индикатора')),
                ('dynamics_type', models.CharField(max_length=100, verbose_name='Тип динамики')),
                ('forecast_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamics_indicators', to='forecast.forecastdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrowthStabilityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Значение индикатора')),
                ('stability_level', models.CharField(max_length=100, verbose_name='Уровень устойчивости')),
                ('forecast_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_stability_indicators', to='forecast.forecastdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonalityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Значение индикатора')),
                ('seasonality_type', models.CharField(max_length=100, verbose_name='Тип сезонности')),
                ('forecast_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonality_indicators', to='forecast.forecastdata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
