# Generated by Django 5.0.4 on 2024-04-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_forecastresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdata',
            name='period_month',
            field=models.IntegerField(verbose_name='Период месяца'),
        ),
    ]
