# Generated by Django 5.0.4 on 2024-04-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_alter_forecastdata_period_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdata',
            name='customer_base',
            field=models.TextField(default='0', verbose_name='Клиентская база'),
        ),
        migrations.AlterField(
            model_name='forecastdata',
            name='employee_count',
            field=models.TextField(default='0', verbose_name='Количество сотрудников'),
        ),
        migrations.AlterField(
            model_name='forecastdata',
            name='net_profit',
            field=models.TextField(default='0', verbose_name='Чистая прибыль'),
        ),
        migrations.AlterField(
            model_name='forecastdata',
            name='operating_expenses',
            field=models.TextField(default='0', verbose_name='Операционные расходы'),
        ),
        migrations.AlterField(
            model_name='forecastdata',
            name='period_month',
            field=models.IntegerField(verbose_name='Период месяца'),
        ),
        migrations.AlterField(
            model_name='forecastdata',
            name='profitability',
            field=models.TextField(default='0', verbose_name='Рентабельность'),
        ),
    ]
