# Generated by Django 5.0.4 on 2024-05-06 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_forecastdata_artefact'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='month',
            field=models.TextField(default='', verbose_name='Месяц прогноза'),
        ),
        migrations.CreateModel(
            name='CoherenceIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Значение индикатора')),
                ('coherence_level', models.CharField(max_length=100, verbose_name='Уровень согласованности')),
                ('forecast_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coherence_indicators', to='forecast.forecastdata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
