# Generated by Django 5.0.4 on 2024-05-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_rename_coherence_level_coherenceindicator_param_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coherenceindicator',
            name='indicator_value',
            field=models.FloatField(verbose_name='Значение индикатора'),
        ),
        migrations.AlterField(
            model_name='dynamicsindicator',
            name='indicator_value',
            field=models.FloatField(verbose_name='Значение индикатора'),
        ),
        migrations.AlterField(
            model_name='growthstabilityindicator',
            name='indicator_value',
            field=models.FloatField(verbose_name='Значение индикатора'),
        ),
        migrations.AlterField(
            model_name='seasonalityindicator',
            name='indicator_value',
            field=models.FloatField(verbose_name='Значение индикатора'),
        ),
    ]
