# Generated by Django 5.0.4 on 2024-05-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0012_forecastresult_seasonal_koef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastresult',
            name='seasonal_koef',
            field=models.FloatField(default=0.0, verbose_name='Расичтанный коэфицицент сезонности'),
        ),
    ]
